#!/bin/bash
# Build the flight test screen with all secure code points

gcc -std=c99 -I./include -o flight_test src/flight_test_screen.c -lm \
  -DTRACING_BUILD \
  -DPATH_CALCULATE_LIFT_COEFFICIENT_EXISTS=1 \
  -DPATH_STALL_DETECTED_EXISTS=1 \
  -DPATH_PHYSICS_UPDATE_START_EXISTS=1 \
  -DPATH_LIFT_CALCULATED_EXISTS=1 \
  -DPATH_FORCES_CALCULATED_EXISTS=1 \
  -DPATH_VELOCITY_UPDATED_EXISTS=1 \
  -DPATH_POSITION_UPDATED_EXISTS=1 \
  -DPATH_STALL_WARNING_ACTIVE_EXISTS=1 \
  -DPATH_GROUND_COLLISION_EXISTS=1 \
  -DPATH_PITCH_UP_INPUT_EXISTS=1 \
  -DPATH_PITCH_DOWN_INPUT_EXISTS=1 \
  -DPATH_ROLL_LEFT_INPUT_EXISTS=1 \
  -DPATH_ROLL_RIGHT_INPUT_EXISTS=1 \
  -DPATH_THRUST_DECREASE_EXISTS=1 \
  -DPATH_THRUST_INCREASE_EXISTS=1 \
  -DPATH_CENTER_CONTROLS_EXISTS=1 \
  -DPATH_INFINITE_FUEL_EXISTS=0 \
  -DPATH_PHYSICS_TELEPORT_EXISTS=0 \
  -DPATH_IGNORE_STALL_EXISTS=0

if [ $? -eq 0 ]; then
    echo "Build successful! Run ./flight_test to start"
else
    echo "Build failed!"
fi